//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServerEduProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Admin_details
    {
        public int admin_id { get; set; }
        public string full_name { get; set; }
        public string email { get; set; }
        public long mobile_no { get; set; }
        public string gender { get; set; }
        public System.DateTime dateof_birth { get; set; }
        public string password { get; set; }
        public string flat_no { get; set; }
        public string street1 { get; set; }
        public string area { get; set; }
        public string city { get; set; }
        public string state { get; set; }
        public int pincode { get; set; }
        public string insert_by { get; set; }
        public Nullable<System.DateTime> insert_date { get; set; }
        public string update_by { get; set; }
        public Nullable<System.DateTime> update_date { get; set; }
        public byte[] admin_image { get; set; }
        public int school_id { get; set; }
    
        public virtual school_details school_details { get; set; }
    }
}
