//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServerEduProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class dairy_details
    {
        public int dairy_id { get; set; }
        public string dairy_class { get; set; }
        public string dairy_section { get; set; }
        public System.DateTime dairy_date { get; set; }
        public string dairy_subject { get; set; }
        public string dairy_units { get; set; }
        public string dairy_todays_work { get; set; }
        public string dairy_todays_homework { get; set; }
        public string insert_by { get; set; }
        public Nullable<System.DateTime> insert_date { get; set; }
        public string update_by { get; set; }
        public Nullable<System.DateTime> update_date { get; set; }
        public int school_id { get; set; }
        public int student_id { get; set; }
        public int teacher_id { get; set; }
    
        public virtual school_details school_details { get; set; }
        public virtual student_details student_details { get; set; }
        public virtual teacher_details teacher_details { get; set; }
    }
}
