//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServerEduProject.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EdujinniEntity : DbContext
    {
        public EdujinniEntity()
            : base("name=EdujinniEntity")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Achievement_details> Achievement_details { get; set; }
        public virtual DbSet<Admin_details> Admin_details { get; set; }
        public virtual DbSet<assignment_details> assignment_details { get; set; }
        public virtual DbSet<attendence_details> attendence_details { get; set; }
        public virtual DbSet<class_details> class_details { get; set; }
        public virtual DbSet<dairy_details> dairy_details { get; set; }
        public virtual DbSet<event_details> event_details { get; set; }
        public virtual DbSet<exam_details> exam_details { get; set; }
        public virtual DbSet<exam_results> exam_results { get; set; }
        public virtual DbSet<examclass_details> examclass_details { get; set; }
        public virtual DbSet<examsubject_details> examsubject_details { get; set; }
        public virtual DbSet<guest_signup> guest_signup { get; set; }
        public virtual DbSet<leaverequest> leaverequests { get; set; }
        public virtual DbSet<school_details> school_details { get; set; }
        public virtual DbSet<Section> Sections { get; set; }
        public virtual DbSet<student_details> student_details { get; set; }
        public virtual DbSet<subject_details> subject_details { get; set; }
        public virtual DbSet<syllabus_details> syllabus_details { get; set; }
        public virtual DbSet<teacher_details> teacher_details { get; set; }
        public virtual DbSet<timetable_details> timetable_details { get; set; }
    }
}
