//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServerEduProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class examclass_details
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public examclass_details()
        {
            this.examsubject_details = new HashSet<examsubject_details>();
        }
    
        public int examclass_id { get; set; }
        public string examclass_class { get; set; }
        public string examclass_section { get; set; }
        public string examclass_exam_type { get; set; }
        public System.DateTime examclass_start_date { get; set; }
        public System.DateTime examclass_end_date { get; set; }
        public string insert_by { get; set; }
        public Nullable<System.DateTime> insert_date { get; set; }
        public string update_by { get; set; }
        public Nullable<System.DateTime> update_date { get; set; }
        public int school_id { get; set; }
        public Nullable<int> section_id { get; set; }
        public Nullable<int> class_id { get; set; }
    
        public virtual school_details school_details { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<examsubject_details> examsubject_details { get; set; }
        public virtual Section Section { get; set; }
    }
}
