//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServerEduProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class student_details
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public student_details()
        {
            this.Achievement_details = new HashSet<Achievement_details>();
            this.assignment_details = new HashSet<assignment_details>();
            this.attendence_details = new HashSet<attendence_details>();
            this.dairy_details = new HashSet<dairy_details>();
            this.exam_results = new HashSet<exam_results>();
        }
    
        public int student_id { get; set; }
        public string student_image { get; set; }
        public string student_section { get; set; }
        public string student_first_name { get; set; }
        public string student_last_name { get; set; }
        public string student_roll_no { get; set; }
        public Nullable<int> student_chiled_no { get; set; }
        public System.DateTime student_dob { get; set; }
        public string student_gender { get; set; }
        public string student_father_name { get; set; }
        public long student_father_mobile_no { get; set; }
        public string student_father_occupation { get; set; }
        public string student_mother_name { get; set; }
        public Nullable<long> student_mother_mobile_no { get; set; }
        public string student_mother_occupation { get; set; }
        public Nullable<int> student_no_of_siblings { get; set; }
        public string student_flat_no { get; set; }
        public string student_buliding_name { get; set; }
        public string student_street { get; set; }
        public string student_street1 { get; set; }
        public string student_area { get; set; }
        public string student_city { get; set; }
        public string student_state { get; set; }
        public int student_pincode { get; set; }
        public string insert_by { get; set; }
        public Nullable<System.DateTime> insert_date { get; set; }
        public string update_by { get; set; }
        public Nullable<System.DateTime> update_date { get; set; }
        public System.DateTime student_admission_date { get; set; }
        public int school_id { get; set; }
        public string Student_status { get; set; }
        public string student_class { get; set; }
        public Nullable<int> section_id { get; set; }
        public Nullable<int> class_id { get; set; }
        public string student_admission_id { get; set; }
        public string student_password { get; set; }
        public string parent_password { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Achievement_details> Achievement_details { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<assignment_details> assignment_details { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<attendence_details> attendence_details { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dairy_details> dairy_details { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<exam_results> exam_results { get; set; }
        public virtual school_details school_details { get; set; }
        public virtual class_details class_details { get; set; }
        public virtual Section Section { get; set; }
    }
}
