//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServerEduProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class subject_details
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public subject_details()
        {
            this.timetable_details = new HashSet<timetable_details>();
        }
    
        public int subject_id { get; set; }
        public string section { get; set; }
        public string subject_type { get; set; }
        public string subject_name { get; set; }
        public string insert_by { get; set; }
        public Nullable<System.DateTime> insert_date { get; set; }
        public string update_by { get; set; }
        public Nullable<System.DateTime> update_date { get; set; }
        public int school_id { get; set; }
        public int class_id { get; set; }
        public int teacher_id { get; set; }
        public Nullable<int> section_id { get; set; }
    
        public virtual class_details class_details { get; set; }
        public virtual school_details school_details { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<timetable_details> timetable_details { get; set; }
        public virtual teacher_details teacher_details { get; set; }
        public virtual Section Section1 { get; set; }
    }
}
